### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [stvnrlly/license_txt#1]
This is awesome! what would be the license?

**Comment by stvnrlly** [comment]
Thanks for catching that ironic oversight. It's a CC0 license.

**Comment by pombredanne** [comment]
@stvnrlly CC0! what a deception! I was expecting something new and Markovian!
Anyway thanks for the quick response!
FWIW, if you want more licenses, check out my list there https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses
